version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install -g npm@latest
  pre_build:
    commands:
      - echo "Linting code..."
      #- npm run lint
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Copying build artifacts to S3 bucket..."
      #- aws s3 sync s3://task-02-02-05
