version: 0.2

phases:
  pre_build:
    commands:
      - echo "Clearing npm cache..."
      - npm cache clean --force
      - echo "Updating npm registry..."
      - npm config set registry https://registry.npmjs.org/
      - echo "Installing dependencies..."
  build:
    commands:
      - npm install
      - echo "Building the project..."
      - npm run build

artifacts:
  files:
    - '**/*'
