version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Update to Node.js 16, which is available in the image.
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build

artifacts:
  files:
    - '**/*'
