version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Adjust Node.js version as needed
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/  # Cache node_modules to speed up future builds
