version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Current working directory: $(pwd)"
      - ls -al  # List directory contents
      - cd /codebuild/output/src62423724/src  # Change to the correct working directory
      - echo "Changed working directory to: $(pwd)"
      - ls -al  # List directory contents again
      - npm install
