version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - cd /codebuild/output/src62423724/src  # Change to the correct working directory
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build

artifacts:
  files:
    - '**/*'
