steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh instance-1 --zone=us-central1-a --command="echo 'Hello from Cloud Build!'"
