steps:
  # Configure Docker to authenticate with gcr.io
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker gcr.io

  # Pull the Docker image by tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/pure-media-413711/github.com/antony-2504/calculator:bf5584fb2058fecec7e03d1d7b3019c79d8363da']

  # Run the Docker container on the instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh antonyavanexa@instance-3 --zone=us-central1-a --command 'sudo docker run -d -p 80:80 gcr.io/pure-media-413711/github.com/antony-2504/calculator:bf5584fb2058fecec7e03d1d7b3019c79d8363da'
