- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - '-c'
    - >
      vmlist=$(gcloud compute instances list --format='value(name)' --filter="labels.name:test AND status:RUNNING") &&
      for vm in $vmlist; do
        gcloud compute ssh cloudbuild@$vm \
          --zone $(gcloud compute instances list --format='value(zone)' --filter="name='$vm'") \
          --quiet --command 'gsutil cp gs://alb234/startup.sh . && sudo chmod +x startup.sh && sudo sh startup.sh'
      done
