steps:
  # Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Antony-2504/calculator.git', '/workspace/repository']

  # Copy all files to the VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --zone=us-central1-a --recurse /workspace/repository/* antonyavanexa@instance-2:/var/test/
