steps:
  # Configure Docker to authenticate with gcr.io
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker

  # Pull the Docker image by tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/pure-media-413711/github.com/antony-2504/calculator@sha256:b144d05e3014243e11dec437f0ce27124aaa5d6ab02d972c4a6c8e56f55c3c84']

  # Run the Docker container on the instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh antonyavanexa@instance-3 --zone=us-central1-a --command 'sudo docker run -d -p 80:80 gcr.io/pure-media-413711/github.com/antony-2504/calculator@sha256:b144d05e3014243e11dec437f0ce27124aaa5d6ab02d972c4a6c8e56f55c3c84'
