steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh instance-2 --zone=us-central1-a -i ~/.ssh/id_rsa --command="echo 'Hello from Cloud Build!'"
